//@ui5-bundle ns/hangman/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"ns/hangman/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","ns/HTML5Module/model/models"],function(e,t,i){"use strict";return e.extend("ns.HTML5Module.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"ns/hangman/controller/View1.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("ns.HTML5Module.controller.View1",{onInit:function(){}})});
},
	"ns/hangman/i18n/i18n.properties":'title=Title\nappTitle=View1\nappDescription=App Description\n',
	"ns/hangman/localService/mockserver.js":function(){sap.ui.define(["sap/ui/core/util/MockServer","sap/ui/model/json/JSONModel","sap/base/util/UriParameters","sap/base/Log"],function(e,t,r,a){"use strict";var o,i="ns/HTML5Module/",n=i+"localService/mockdata";var s={init:function(s){var u=s||{};return new Promise(function(s,c){var p=sap.ui.require.toUrl(i+"manifest.json"),l=new t(p);l.attachRequestCompleted(function(){var t=new r(window.location.href),c=sap.ui.require.toUrl(n),p=l.getProperty("/sap.app/dataSources/mainService"),f=sap.ui.require.toUrl(i+p.settings.localUri),d=p.uri&&new URI(p.uri).absoluteTo(sap.ui.require.toUrl(i)).toString();if(!o){o=new e({rootUri:d})}else{o.stop()}e.config({autoRespond:true,autoRespondAfter:u.delay||t.get("serverDelay")||500});o.simulate(f,{sMockdataBaseUrl:c,bGenerateMissingMockData:true});var m=o.getRequests();var v=function(e,t,r){r.response=function(r){r.respond(e,{"Content-Type":"text/plain;charset=utf-8"},t)}};if(u.metadataError||t.get("metadataError")){m.forEach(function(e){if(e.path.toString().indexOf("$metadata")>-1){v(500,"metadata Error",e)}})}var g=u.errorType||t.get("errorType"),h=g==="badRequest"?400:500;if(g){m.forEach(function(e){v(h,g,e)})}o.setRequests(m);o.start();a.info("Running the app with mock data");s()});l.attachRequestFailed(function(){var e="Failed to load application manifest";a.error(e);c(new Error(e))})})},getMockServer:function(){return o}};return s});
},
	"ns/hangman/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"ns.hangman","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach","sourceTemplate":{"id":"html5moduletemplates.basicSAPUI5ApplicationProjectModule","version":"1.40.12"}},"sap.cloud":{"public":true,"service":"photo.wall"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"ns.HTML5Module.view.View1","type":"XML","async":true,"id":"View1"},"dependencies":{"minUI5Version":"1.60.1","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"ns.HTML5Module.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"ns.HTML5Module.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView1","pattern":"RouteView1","target":["TargetView1"]}],"targets":{"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"}}}}}',
	"ns/hangman/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"ns/hangman/photo-script.js":function(){startRecording=function(){var e=document.getElementById("video");if(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia){navigator.mediaDevices.getUserMedia({video:true}).then(function(t){e.srcObject=t;e.play()})}else{console.log("No access to camera...")}document.getElementById("video").style.display="block";document.getElementById("canvas").style.display="none";document.getElementById("snap").style.display="inline";document.getElementById("reset").style.display="none";document.getElementById("send").style.display="none"};stopRecording=function(){video.pause();video.src="";var e=video.srcObject.getTracks();for(i in e){e[i].stop()}};document.addEventListener("DOMContentLoaded",function(e){document.getElementById("create").addEventListener("click",function(){document.getElementById("photo").style.display="none"});document.getElementById("photo").addEventListener("click",function(){document.getElementById("photo-dialog").setAttribute("class","fd-dialog-docs-static fd-dialog fd-dialog--active");startRecording()});document.getElementById("photo-dialog-close").addEventListener("click",function(){document.getElementById("photo-dialog").setAttribute("class","fd-dialog-docs-static fd-dialog");stopRecording()});var t=document.getElementById("canvas");var n=t.getContext("2d");var d=document.getElementById("video");document.getElementById("snap").addEventListener("click",function(){n.drawImage(d,0,0,400,300);document.getElementById("video").style.display="none";document.getElementById("canvas").style.display="block";document.getElementById("snap").style.display="none";document.getElementById("reset").style.display="inline";document.getElementById("send").style.display="inline"});document.getElementById("reset").addEventListener("click",function(){document.getElementById("video").style.display="block";document.getElementById("canvas").style.display="none";document.getElementById("snap").style.display="inline";document.getElementById("reset").style.display="none";document.getElementById("send").style.display="none"});document.getElementById("send").addEventListener("click",function(){var e=document.getElementById("canvas");fetch("photo-wall",{method:"POST",headers:{"Content-Type":"image/png",filekey:"key-"+Date.now()},body:e.toDataURL("image/png")});document.getElementById("photo-dialog").setAttribute("class","fd-dialog-docs-static fd-dialog");document.getElementById("photo").style.display="none";stopRecording()})});
},
	"ns/hangman/script.js":'var urlParams=new URLSearchParams(window.location.search);var game;var characters=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"];onAPIError=function(){document.getElementById("title").innerText="Error in API Call :/"};onDataLoaded=function(e){game=e.id;document.getElementById("title").innerText="Good luck!";document.getElementById("characters").style.display="block";document.getElementById("picture").style.display="block";document.getElementById("word").style.display="block";document.getElementById("create").style.display="none";document.getElementById("word").innerText="test";document.getElementById("picture").src="img/"+(6-e.lives)+".png";document.getElementById("word").innerText=e.word;for(var t=0;t<characters.length;t++){document.getElementById("char-"+characters[t]).setAttribute("aria-disabled",e.guesses.includes(characters[t]))}if(e.lives<1){document.getElementById("title").innerText="You loose!";document.getElementById("characters").style.display="none";document.getElementById("create").style.display="inline"}else if(!e.word.includes("_")){document.getElementById("title").innerText="You win!";document.getElementById("characters").style.display="none";document.getElementById("create").style.display="inline";document.getElementById("photo").style.display="inline"}};onButtonPressed=async function(){var e=this.innerText;let t=await fetch("api/games/"+game+"/guesses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({value:e})});if(!t.ok){onAPIError()}else{t.json().then(e=>onDataLoaded(e))}};onCreateGame=async function(){let e=await fetch("api/games/",{method:"POST"});if(!e.ok){onAPIError()}else{e.json().then(e=>onDataLoaded(e))}};document.addEventListener("DOMContentLoaded",function(){for(i in characters){var e=document.createElement("button");e.setAttribute("class","fd-button");e.setAttribute("id","char-"+characters[i]);e.innerText=characters[i];document.getElementById("characters").append(e);document.getElementById("char-"+characters[i]).addEventListener("click",onButtonPressed)}document.getElementById("characters").style.display="none";document.getElementById("picture").style.display="none";document.getElementById("word").style.display="none";document.getElementById("title").style.display="block";document.getElementById("create").style.display="inline";document.getElementById("create").addEventListener("click",onCreateGame)});',
	"ns/hangman/view/View1.view.xml":'<mvc:View controllerName="ns.HTML5Module.controller.View1" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><content></content></Page></pages></App></Shell></mvc:View>\n'
}});
